# Generated by Django 4.2 on 2026-04-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('place_of_aid', models.CharField(blank=True, max_length=100)),
                ('date_of_aid', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AidRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AidRequestProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(blank=True, choices=[('medical', 'Medical'), ('financial', 'Financial')], max_length=20)),
                ('aid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_of_aid_amount', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('aid_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid_providers.aidprovider')),
                ('aid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='aid_requests.aidrequest')),
            ],
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='aid_request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aid_requests.aidrequesttype'),
        ),
    ]
