# Generated by Django 4.2 on 2026-04-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid_requests', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='aidrequestprovider',
            unique_together={('aid_request', 'aid_provider')},
        ),
    ]
