# Generated by Django 4.2 on 2026-04-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aidrequestprovider',
            unique_together=set(),
        ),
    ]
