# Generated by Django 4.2 on 2026-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mother_full_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('national_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('family_booklet_no', models.CharField(blank=True, max_length=100)),
                ('current_residence', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('telephone_number', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('home_status', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family_owned', 'Family Owned')], max_length=20)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_needs', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
